DROP TABLE IF EXISTS performances;
CREATE TABLE performances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nageur TEXT NOT NULL,
  epreuve TEXT NOT NULL,
  bassin TEXT NOT NULL,
  date DATE NOT NULL,
  temps_texte TEXT NOT NULL,
  secondes NUMERIC NOT NULL
);

ALTER TABLE performances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anon select" ON performances FOR SELECT TO anon USING (true);
CREATE POLICY "Allow anon insert" ON performances FOR INSERT TO anon WITH CHECK (true);
